install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.60.0/hugo_extended_0.60.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  fqdn: rifkiaz.web.id
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: source
