install:
  - wget -O /tmp/hugo.deb http://archive.ubuntu.com/ubuntu/pool/universe/h/hugo/hugo_0.68.3-1_amd64.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  fqdn: blog.rifkiaz.web.id
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: source
