baseurl = "https://blog.rifkiaz.web.id/"
title = "Coretan dan Catetan Oprek"
copyright = "Copyright &copy; 2020 - Rifki Affandi"
canonifyurls = true
theme = "hugo-theme-fuji"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "rifkiaz"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Rifki Affandi"
    github = "rifkiaz"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "rifkiiaz"
    instagram = "rifkiaz"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "Hanya catatan biasa terkait tutorial FLOSS"
    description = "Kiera: A Hugo theme for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1

  # Show scroll to top button
  scrollTop = true

  # License
  license = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)"
  licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/rifkiaz"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/rifkiiaz"
    weight = 2
  [[menu.link]]
    name = "Instagram"
    url = "https://instagram.com/rifkiaz"
    weight = 3

